--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      FI.UNAM
-- Project :      Model.DM1
-- Author :       Cristobal Garcia
--
-- Date Created : Tuesday, December 27, 2022 13:39:35
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: BANCO 
--

CREATE TABLE BANCO(
    BANCO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE      VARCHAR2(50)     NOT NULL,
    CONSTRAINT PK21_1 PRIMARY KEY (BANCO_ID)
)
;



-- 
-- TABLE: TIPO_SERVICIO 
--

CREATE TABLE TIPO_SERVICIO(
    TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(50)     NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (TIPO_SERVICIO_ID)
)
;



-- 
-- TABLE: ENTIDAD_FEDERATIVA 
--

CREATE TABLE ENTIDAD_FEDERATIVA(
    ENTIDAD_FEDERATIVA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(50)     NOT NULL,
    CONSTRAINT PK21 PRIMARY KEY (ENTIDAD_FEDERATIVA_ID)
)
;



-- 
-- TABLE: ESTATUS_PROVEEDOR 
--

CREATE TABLE ESTATUS_PROVEEDOR(
    ESTATUS_PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(50)     NOT NULL,
    DESCRIPCION             VARCHAR2(500)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (ESTATUS_PROVEEDOR_ID)
)
;



-- 
-- TABLE: NIVEL_ESTUDIO 
--

CREATE TABLE NIVEL_ESTUDIO(
    NIVEL_ESTUDIO_ID    NUMBER(10, 0)    NOT NULL,
    NIVEL_ESTUDIO       VARCHAR2(200)    NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    CONSTRAINT PK41 PRIMARY KEY (NIVEL_ESTUDIO_ID)
)
;



-- 
-- TABLE: PROVEEDOR 
--

CREATE TABLE PROVEEDOR(
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(50)     NOT NULL,
    AP_PATERNO               VARCHAR2(30)     NOT NULL,
    AP_MATERNO               VARCHAR2(30)     NOT NULL,
    FOTO                     BLOB             NOT NULL,
    FECHA_NACIMIENTO         DATE             NOT NULL,
    DIRECCION                VARCHAR2(200)    NOT NULL,
    TELEFONO_CASA            NUMBER(10, 0)    NOT NULL,
    TELEFONO_MOVIL           VARCHAR2(40)     NOT NULL,
    IDENTIFICACION           BLOB             NOT NULL,
    COMPROBANTE_DOMICILIO    BLOB             NOT NULL,
    FECHA_ESTATUS            DATE             NOT NULL,
    ENTIDAD_FEDERATIVA_ID    NUMBER(10, 0)    NOT NULL,
    ESTATUS_PROVEEDOR_ID     NUMBER(10, 0)    NOT NULL,
    NIVEL_ESTUDIO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK16 PRIMARY KEY (PROVEEDOR_ID), 
    CONSTRAINT RefENTIDAD_FEDERATIVA22 FOREIGN KEY (ENTIDAD_FEDERATIVA_ID)
    REFERENCES ENTIDAD_FEDERATIVA(ENTIDAD_FEDERATIVA_ID),
    CONSTRAINT RefESTATUS_PROVEEDOR82 FOREIGN KEY (ESTATUS_PROVEEDOR_ID)
    REFERENCES ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID),
    CONSTRAINT RefNIVEL_ESTUDIO322 FOREIGN KEY (NIVEL_ESTUDIO_ID)
    REFERENCES NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID)
)
;



-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE_ID        NUMBER(10, 0)    NOT NULL,
    FECHA_REGISTRO    DATE             NOT NULL,
    NOMBRE_USUARIO    VARCHAR2(100)    NOT NULL,
    CONTRASENIA       VARCHAR2(500)    NOT NULL,
    "EMAIL."          VARCHAR2(50)     NOT NULL,
    TELEFONO          NUMBER(10, 0)    NOT NULL,
    DIRECCION         VARCHAR2(300)    NOT NULL,
    TIPO              CHAR(1)          NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: ESTATUS_SERVICIO 
--

CREATE TABLE ESTATUS_SERVICIO(
    ESTATUS_CONTRATO_ID    CHAR(10)        NOT NULL,
    NOMBRE                 VARCHAR2(30)    NOT NULL,
    DESCRIPCION            VARCHAR2(50)    NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (ESTATUS_CONTRATO_ID)
)
;



-- 
-- TABLE: HISTORICO_ESTATUS_SERVICIO 
--

CREATE TABLE HISTORICO_ESTATUS_SERVICIO(
    HISTORICO_ESTATUS_CONTRATO_ID    VARCHAR2(10)    NOT NULL,
    FECHA_ESTATUS                    DATE            NOT NULL,
    ESTATUS_CONTRATO_ID              CHAR(10)        NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (HISTORICO_ESTATUS_CONTRATO_ID), 
    CONSTRAINT RefESTATUS_SERVICIO162 FOREIGN KEY (ESTATUS_CONTRATO_ID)
    REFERENCES ESTATUS_SERVICIO(ESTATUS_CONTRATO_ID)
)
;



-- 
-- TABLE: SERVICIO 
--

CREATE TABLE SERVICIO(
    SERVICIO_ID                      NUMBER(10, 0)     NOT NULL,
    FECHA_SERVICIO                   DATE              NOT NULL,
    DESCRIPCION_SERVICIO             VARCHAR2(1000)    NOT NULL,
    DESCRIPCION_DETALLADA            BLOB              NOT NULL,
    FECHA_ESTATUS                    DATE              NOT NULL,
    PRECIO                           NUMBER(10, 0)     NOT NULL,
    INSTRUCCIONES                    VARCHAR2(500)     NOT NULL,
    MENSUALIDADES                    NUMBER(10, 0),
    PROVEEDOR_ID                     NUMBER(10, 0)     NOT NULL,
    CLIENTE_ID                       NUMBER(10, 0)     NOT NULL,
    HISTORICO_ESTATUS_CONTRATO_ID    VARCHAR2(10)      NOT NULL,
    ESTATUS_CONTRATO_ID              CHAR(10)          NOT NULL,
    TIPO_SERVICIO_ID                 NUMBER(10, 0)     NOT NULL,
    CONSTRAINT PK40 PRIMARY KEY (SERVICIO_ID), 
    CONSTRAINT RefTIPO_SERVICIO582 FOREIGN KEY (TIPO_SERVICIO_ID)
    REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID),
    CONSTRAINT RefPROVEEDOR342 FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT RefCLIENTE362 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT RefHISTORICO_ESTATUS_SERVIC372 FOREIGN KEY (HISTORICO_ESTATUS_CONTRATO_ID)
    REFERENCES HISTORICO_ESTATUS_SERVICIO(HISTORICO_ESTATUS_CONTRATO_ID),
    CONSTRAINT RefESTATUS_SERVICIO382 FOREIGN KEY (ESTATUS_CONTRATO_ID)
    REFERENCES ESTATUS_SERVICIO(ESTATUS_CONTRATO_ID)
)
;



-- 
-- TABLE: CALIFICACION 
--

CREATE TABLE CALIFICACION(
    CALIFICACION_ID    NUMBER(10, 0)    NOT NULL,
    COMENTARIO         VARCHAR2(500),
    CALIFICACION       NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (CALIFICACION_ID), 
    CONSTRAINT RefSERVICIO502 FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
)
;



-- 
-- TABLE: PROVEEDOR_TIPO_SERVICIO 
--

CREATE TABLE PROVEEDOR_TIPO_SERVICIO(
    PROVEEDOR_TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    ANIOS_EXPERIENCIA             NUMBER(10, 0)    NOT NULL,
    PROVEEDOR_ID                  NUMBER(10, 0)    NOT NULL,
    TIPO_SERVICIO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (PROVEEDOR_TIPO_SERVICIO_ID), 
    CONSTRAINT RefTIPO_SERVICIO262 FOREIGN KEY (TIPO_SERVICIO_ID)
    REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID),
    CONSTRAINT RefPROVEEDOR272 FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
;



-- 
-- TABLE: COMPROBANTE_EXPERIENCIA 
--

CREATE TABLE COMPROBANTE_EXPERIENCIA(
    COMPROBANTE_EXPERIENCIA_ID    NUMBER(10, 0)    NOT NULL,
    TITULO_COMPROBANTE            VARCHAR2(100)    NOT NULL,
    CONTENIDO                     BLOB             NOT NULL,
    FECHA_COMPROBANTE             DATE             NOT NULL,
    PROVEEDOR_TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK42 PRIMARY KEY (COMPROBANTE_EXPERIENCIA_ID), 
    CONSTRAINT RefPROVEEDOR_TIPO_SERVICIO332 FOREIGN KEY (PROVEEDOR_TIPO_SERVICIO_ID)
    REFERENCES PROVEEDOR_TIPO_SERVICIO(PROVEEDOR_TIPO_SERVICIO_ID)
)
;



-- 
-- TABLE: CUENTA_BANCARIA 
--

CREATE TABLE CUENTA_BANCARIA(
    CUENTA_BANCARIA_ID    NUMBER(10, 0)    NOT NULL,
    CLABE                 VARCHAR2(255)    NOT NULL,
    PROVEEDOR_ID          NUMBER(10, 0)    NOT NULL,
    BANCO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK19_1 PRIMARY KEY (CUENTA_BANCARIA_ID), 
    CONSTRAINT RefPROVEEDOR122 FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT RefBANCO142 FOREIGN KEY (BANCO_ID)
    REFERENCES BANCO(BANCO_ID)
)
;



-- 
-- TABLE: DEPOSITO 
--

CREATE TABLE DEPOSITO(
    DEPOSITO_ID           NUMBER(10, 0)    NOT NULL,
    IMPORTE               NUMBER(10, 0)    NOT NULL,
    FECHA_DEPOSITO        DATE             NOT NULL,
    COMPROBANTE_PAGO      BLOB             NOT NULL,
    CUENTA_BANCARIA_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK20_1 PRIMARY KEY (DEPOSITO_ID), 
    CONSTRAINT RefCUENTA_BANCARIA132 FOREIGN KEY (CUENTA_BANCARIA_ID)
    REFERENCES CUENTA_BANCARIA(CUENTA_BANCARIA_ID)
)
;



-- 
-- TABLE: EMAIL 
--

CREATE TABLE EMAIL(
    EMAIL_ID        NUMBER(10, 0)    NOT NULL,
    PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,
    EMAIL           VARCHAR2(200)    NOT NULL,
    CONSTRAINT PK39 PRIMARY KEY (EMAIL_ID, PROVEEDOR_ID), 
    CONSTRAINT RefPROVEEDOR302 FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
;



-- 
-- TABLE: EMPRESA 
--

CREATE TABLE EMPRESA(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    NOMBRE              VARCHAR2(200)    NOT NULL,
    LOGOTIPO            BLOB             NOT NULL,
    NUMERO_EMPLEADOS    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (CLIENTE_ID), 
    CONSTRAINT RefCLIENTE192 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: EVIDENCIA_SERVICIO 
--

CREATE TABLE EVIDENCIA_SERVICIO(
    EVIDENCIA_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA                    DATE             NOT NULL,
    DESCRIPCION              VARCHAR2(500)    NOT NULL,
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK16_1 PRIMARY KEY (EVIDENCIA_SERVICIO_ID), 
    CONSTRAINT RefPROVEEDOR292 FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
;



-- 
-- TABLE: HISTORICO_ESTATUS_PROVEEDOR 
--

CREATE TABLE HISTORICO_ESTATUS_PROVEEDOR(
    HISTORICO_ESTATUS_PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_ESTATUS                     DATE             NOT NULL,
    ESTATUS_PROVEEDOR_ID              NUMBER(10, 0)    NOT NULL,
    PROVEEDOR_ID                      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK20 PRIMARY KEY (HISTORICO_ESTATUS_PROVEEDOR_ID), 
    CONSTRAINT RefESTATUS_PROVEEDOR92 FOREIGN KEY (ESTATUS_PROVEEDOR_ID)
    REFERENCES ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID),
    CONSTRAINT RefPROVEEDOR102 FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
;



-- 
-- TABLE: IMAGEN 
--

CREATE TABLE IMAGEN(
    IMAGEN_ID                NUMBER(10, 0)    NOT NULL,
    DESCRIPCION              VARCHAR2(500),
    ARCHIVO                  BLOB             NOT NULL,
    EVIDENCIA_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK17 PRIMARY KEY (IMAGEN_ID), 
    CONSTRAINT RefEVIDENCIA_SERVICIO282 FOREIGN KEY (EVIDENCIA_SERVICIO_ID)
    REFERENCES EVIDENCIA_SERVICIO(EVIDENCIA_SERVICIO_ID)
)
;



-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    TARJETA_ID          NUMBER(10, 0)    NOT NULL,
    NUMERO              NUMBER(16, 0)    NOT NULL,
    FECHA_EXPIRACION    DATE             NOT NULL,
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (TARJETA_ID), 
    CONSTRAINT RefCLIENTE212 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: PAGO 
--

CREATE TABLE PAGO(
    PAGO_ID        NUMBER(10, 0)    NOT NULL,
    TARJETA_ID     NUMBER(10, 0)    NOT NULL,
    FECHA_PAGO     DATE,
    IMPORTE        NUMBER(10, 0)    NOT NULL,
    COMISION       NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK11_1 PRIMARY KEY (PAGO_ID, TARJETA_ID), 
    CONSTRAINT RefTARJETA222 FOREIGN KEY (TARJETA_ID)
    REFERENCES TARJETA(TARJETA_ID),
    CONSTRAINT RefSERVICIO392 FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
)
;



-- 
-- TABLE: PERSONA 
--

CREATE TABLE PERSONA(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(200)    NOT NULL,
    FOTO                BLOB             NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (CLIENTE_ID), 
    CONSTRAINT RefCLIENTE202 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



