--@Autor: Oswaldo Cabrera Pérez y Edgar García
--@Fecha creación: 27/12/2022
--@Descripción: Creacion de las tablas y foreign keys de la base de datos

--

-- 
-- TABLE: BANCO 
--

WHENEVER SQLERROR EXIT ROLLBACK;

CREATE TABLE BANCO(
    BANCO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE      VARCHAR2(50)     NOT NULL,
    CONSTRAINT BANCO_PK PRIMARY KEY (BANCO_ID)
)
;



-- 
-- TABLE: TIPO_SERVICIO 
--

CREATE TABLE TIPO_SERVICIO(
    TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(50)     NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    CONSTRAINT TIPO_SERVICIO_PK PRIMARY KEY (TIPO_SERVICIO_ID)
)
;


-- 
-- TABLE: ENTIDAD_FEDERATIVA 
--

CREATE TABLE ENTIDAD_FEDERATIVA(
    ENTIDAD_FEDERATIVA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(50)     NOT NULL,
    CONSTRAINT ENTIDAD_FEDERATIVA_PK PRIMARY KEY (ENTIDAD_FEDERATIVA_ID)
)
;



-- 
-- TABLE: ESTATUS_PROVEEDOR 
--

CREATE TABLE ESTATUS_PROVEEDOR(
    ESTATUS_PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(50)     NOT NULL,
    DESCRIPCION             VARCHAR2(500)    NOT NULL,
    CONSTRAINT ESTATUS_PROVEEDOR_PK PRIMARY KEY (ESTATUS_PROVEEDOR_ID)
)
;



-- 
-- TABLE: NIVEL_ESTUDIO 
--

CREATE TABLE NIVEL_ESTUDIO(
    NIVEL_ESTUDIO_ID    NUMBER(10, 0)    NOT NULL,
    NIVEL_ESTUDIO       VARCHAR2(200)    NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    CONSTRAINT NIVEL_ESTUDIO_PK PRIMARY KEY (NIVEL_ESTUDIO_ID)
)
;



-- 
-- TABLE: PROVEEDOR 
--


CREATE TABLE PROVEEDOR(
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(50)     NOT NULL,
    AP_PATERNO               VARCHAR2(30)     NOT NULL,
    AP_MATERNO               VARCHAR2(30)     NOT NULL,
    FOTO                     BLOB             NOT NULL,
    FECHA_NACIMIENTO         DATE             NOT NULL,
    DIRECCION                VARCHAR2(200)    NOT NULL,
    TELEFONO_CASA            NUMBER(10, 0)    NOT NULL,
    TELEFONO_MOVIL           VARCHAR2(40)     NOT NULL,
    IDENTIFICACION           BLOB             NOT NULL,
    COMPROBANTE_DOMICILIO    BLOB             NOT NULL,
    FECHA_ESTATUS            DATE             NOT NULL,
    ENTIDAD_FEDERATIVA_ID    NUMBER(10, 0)    NOT NULL,
    ESTATUS_PROVEEDOR_ID     NUMBER(10, 0)    NOT NULL,
    NIVEL_ESTUDIO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (PROVEEDOR_ID), 
    CONSTRAINT PROV_ENTIDAD_FEDERATIVA_ID_FK FOREIGN KEY (ENTIDAD_FEDERATIVA_ID)
      REFERENCES ENTIDAD_FEDERATIVA(ENTIDAD_FEDERATIVA_ID),
    CONSTRAINT PROV_ESTATUS_PROVEEDOR_ID_FK FOREIGN KEY (ESTATUS_PROVEEDOR_ID)
      REFERENCES ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID),
    CONSTRAINT PROV_NIVEL_ESTUDIO_ID_FK FOREIGN KEY (NIVEL_ESTUDIO_ID)
      REFERENCES NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID)
)
;



-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE_ID        NUMBER(10, 0)    NOT NULL,
    FECHA_REGISTRO    DATE             NOT NULL,
    NOMBRE_USUARIO    VARCHAR2(100)    NOT NULL,
    CONTRASENIA       VARCHAR2(500)    NOT NULL,
    EMAIL             VARCHAR2(50)     NOT NULL,
    TELEFONO          NUMBER(10, 0)    NOT NULL,
    DIRECCION         VARCHAR2(300)    NOT NULL,
    TIPO              CHAR(1)          NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: ESTATUS_SERVICIO 
--

CREATE TABLE ESTATUS_SERVICIO(
    ESTATUS_SERVICIO_ID    CHAR(10)        NOT NULL,
    NOMBRE                 VARCHAR2(30)    NOT NULL,
    DESCRIPCION            VARCHAR2(50)    NOT NULL,
    CONSTRAINT ESTATUS_SERVICIO_PK PRIMARY KEY (ESTATUS_SERVICIO_ID)
)
;



-- 
-- TABLE: HISTORICO_ESTATUS_SERVICIO 
--

CREATE TABLE HISTORICO_ESTATUS_SERVICIO(
    HISTORICO_ESTATUS_SERVICIO_ID    VARCHAR2(10)    NOT NULL,
    FECHA_ESTATUS                    DATE            NOT NULL,
    ESTATUS_SERVICIO_ID              CHAR(10)        NOT NULL,
    CONSTRAINT HISTORICO_ESTATUS_PROVEEDOR_PK 
      PRIMARY KEY (HISTORICO_ESTATUS_SERVICIO_ID), 
    CONSTRAINT HES_ESTATUS_SERVICIO_ID_FK FOREIGN KEY (ESTATUS_SERVICIO_ID)
      REFERENCES ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID)
)
;



-- 
-- TABLE: SERVICIO 
--

CREATE TABLE SERVICIO(
    SERVICIO_ID                      NUMBER(10, 0)     NOT NULL,
    FECHA_SERVICIO                   DATE              NOT NULL,
    DESCRIPCION_SERVICIO             VARCHAR2(1000)    NOT NULL,
    DESCRIPCION_DETALLADA            BLOB              NOT NULL,
    FECHA_ESTATUS                    DATE              NOT NULL,
    PRECIO                           NUMBER(10, 0)     NOT NULL,
    INSTRUCCIONES                    VARCHAR2(500)     NOT NULL,
    MENSUALIDADES                    NUMBER(10, 0),
    PROVEEDOR_ID                     NUMBER(10, 0)     NOT NULL,
    CLIENTE_ID                       NUMBER(10, 0)     NOT NULL,
    HISTORICO_ESTATUS_SERVICIO_ID    VARCHAR2(10)      NOT NULL,
    ESTATUS_SERVICIO_ID              CHAR(10)          NOT NULL,
    TIPO_SERVICIO_ID                 NUMBER(10, 0)     NOT NULL,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (SERVICIO_ID), 
    CONSTRAINT SERV_TIPO_SERVICIO_ID_FK FOREIGN KEY (TIPO_SERVICIO_ID)
      REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID),
    CONSTRAINT SERV_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT SERV_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT SERV_HISTORICO_ESTATUS_SERVICIO_ID_FK 
      FOREIGN KEY (HISTORICO_ESTATUS_SERVICIO_ID)
        REFERENCES HISTORICO_ESTATUS_SERVICIO(HISTORICO_ESTATUS_SERVICIO_ID),
    CONSTRAINT SERV_ESTATUS_SERVICIO_ID_FK FOREIGN KEY (ESTATUS_SERVICIO_ID)
      REFERENCES ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID)
)
;



-- 
-- TABLE: CALIFICACION 
--

CREATE TABLE CALIFICACION(
    CALIFICACION_ID    NUMBER(10, 0)    NOT NULL,
    COMENTARIO         VARCHAR2(500),
    CALIFICACION       NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CALIFICACION_PK PRIMARY KEY (CALIFICACION_ID), 
    CONSTRAINT CALIFICACION_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID)
      REFERENCES SERVICIO(SERVICIO_ID)
)
;



-- 
-- TABLE: PROVEEDOR_TIPO_SERVICIO 
--

CREATE TABLE PROVEEDOR_TIPO_SERVICIO(
    PROVEEDOR_TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    ANIOS_EXPERIENCIA             NUMBER(10, 0)    NOT NULL,
    PROVEEDOR_ID                  NUMBER(10, 0)    NOT NULL,
    TIPO_SERVICIO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PROVEEDOR_TIPO_SERVICIO_PK 
      PRIMARY KEY (PROVEEDOR_TIPO_SERVICIO_ID), 
    CONSTRAINT PROV_TS_TIPO_SERVICIO_ID_FK FOREIGN KEY (TIPO_SERVICIO_ID)
      REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID),
    CONSTRAINT PROV_TS_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
;



-- 
-- TABLE: COMPROBANTE_EXPERIENCIA 
--

CREATE TABLE COMPROBANTE_EXPERIENCIA(
    COMPROBANTE_EXPERIENCIA_ID    NUMBER(10, 0)    NOT NULL,
    TITULO_COMPROBANTE            VARCHAR2(100)    NOT NULL,
    CONTENIDO                     BLOB             NOT NULL,
    FECHA_COMPROBANTE             DATE             NOT NULL,
    PROVEEDOR_TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT COMPROBANTE_EXPERIENCIA_PK 
      PRIMARY KEY (COMPROBANTE_EXPERIENCIA_ID), 
    CONSTRAINT CE_PROVEEDOR_TIPO_SERVICIO_ID_PK 
      FOREIGN KEY (PROVEEDOR_TIPO_SERVICIO_ID)
        REFERENCES PROVEEDOR_TIPO_SERVICIO(PROVEEDOR_TIPO_SERVICIO_ID)
)
;



-- 
-- TABLE: CUENTA_BANCARIA 
--

CREATE TABLE CUENTA_BANCARIA(
    CUENTA_BANCARIA_ID    NUMBER(10, 0)    NOT NULL,
    CLABE                 VARCHAR2(255)    NOT NULL,
    PROVEEDOR_ID          NUMBER(10, 0)    NOT NULL,
    BANCO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CUENTA_BANCARIA_PK PRIMARY KEY (CUENTA_BANCARIA_ID), 
    CONSTRAINT CB_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT CB_BANCO_ID_FK FOREIGN KEY (BANCO_ID)
      REFERENCES BANCO(BANCO_ID)
)
;


-- 
-- TABLE: DEPOSITO 
--

CREATE TABLE DEPOSITO(
    DEPOSITO_ID           NUMBER(10, 0)    NOT NULL,
    IMPORTE               NUMBER(10, 0)    NOT NULL,
    FECHA_DEPOSITO        DATE             NOT NULL,
    COMPROBANTE_PAGO      BLOB             NOT NULL,
    CUENTA_BANCARIA_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT DEPOSITO_PK PRIMARY KEY (DEPOSITO_ID), 
    CONSTRAINT DEPOSITO_CUENTA_BANCARIA_ID_FK FOREIGN KEY (CUENTA_BANCARIA_ID)
      REFERENCES CUENTA_BANCARIA(CUENTA_BANCARIA_ID)
)
;



-- 
-- TABLE: EMAIL 
--

CREATE TABLE EMAIL(
    EMAIL_ID        NUMBER(10, 0)    NOT NULL,
    PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,
    EMAIL           VARCHAR2(200)    NOT NULL,
    CONSTRAINT EMAIL_PK PRIMARY KEY (EMAIL_ID, PROVEEDOR_ID), 
    CONSTRAINT EMAIL_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
;



-- 
-- TABLE: EMPRESA 
--

CREATE TABLE EMPRESA(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    NOMBRE              VARCHAR2(200)    NOT NULL,
    LOGOTIPO            BLOB             NOT NULL,
    NUMERO_EMPLEADOS    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EMPRESA_PK PRIMARY KEY (CLIENTE_ID), 
    CONSTRAINT EMPRESA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: EVIDENCIA_SERVICIO 
--

CREATE TABLE EVIDENCIA_SERVICIO(
    EVIDENCIA_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA                    DATE             NOT NULL,
    DESCRIPCION              VARCHAR2(500)    NOT NULL,
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EVIDENCIA_SERVICIO_PK PRIMARY KEY (EVIDENCIA_SERVICIO_ID), 
    CONSTRAINT EVIDENCIA_SERVICIO_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
;



-- 
-- TABLE: HISTORICO_ESTATUS_PROVEEDOR 
--

CREATE TABLE HISTORICO_ESTATUS_PROVEEDOR(
    HISTORICO_ESTATUS_PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_ESTATUS                     DATE             NOT NULL,
    ESTATUS_PROVEEDOR_ID              NUMBER(10, 0)    NOT NULL,
    PROVEEDOR_ID                      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_ESTATUS_PROVEEDOR_PK 
      PRIMARY KEY (HISTORICO_ESTATUS_PROVEEDOR_ID), 
    CONSTRAINT HISTORICO_ESTATUS_PROVEEDOR_ESTATUS_PROVEEDOR_ID_FK 
      FOREIGN KEY (ESTATUS_PROVEEDOR_ID)
        REFERENCES ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID),
    CONSTRAINT HISTORICO_ESTATUS_PROVEEDOR_PROVEEDOR_ID_FK 
      FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
;



-- 
-- TABLE: IMAGEN 
--

CREATE TABLE IMAGEN(
    IMAGEN_ID                NUMBER(10, 0)    NOT NULL,
    DESCRIPCION              VARCHAR2(500),
    ARCHIVO                  BLOB             NOT NULL,
    EVIDENCIA_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT IMAGEN_PK PRIMARY KEY (IMAGEN_ID), 
    CONSTRAINT IMAGEN_EVUDENCIA_SERVICIO_ID_FK 
      FOREIGN KEY (EVIDENCIA_SERVICIO_ID)
        REFERENCES EVIDENCIA_SERVICIO(EVIDENCIA_SERVICIO_ID)
)
;



-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    TARJETA_ID          NUMBER(10, 0)    NOT NULL,
    NUMERO              NUMBER(16, 0)    NOT NULL,
    FECHA_EXPIRACION    DATE             NOT NULL,
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT TARJETA_PK PRIMARY KEY (TARJETA_ID), 
    CONSTRAINT TARJETA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: PAGO 
--

CREATE TABLE PAGO(
    PAGO_ID        NUMBER(10, 0)    NOT NULL,
    TARJETA_ID     NUMBER(10, 0)    NOT NULL,
    FECHA_PAGO     DATE,
    IMPORTE        NUMBER(10, 0)    NOT NULL,
    COMISION       NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PAGO_PK PRIMARY KEY (PAGO_ID, TARJETA_ID), 
    CONSTRAINT PAGO_TARJETA_ID_FK FOREIGN KEY (TARJETA_ID)
      REFERENCES TARJETA(TARJETA_ID),
    CONSTRAINT PAGO_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID)
      REFERENCES SERVICIO(SERVICIO_ID)
)
;



-- 
-- TABLE: PERSONA 
--

CREATE TABLE PERSONA(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(200)    NOT NULL,
    FOTO                BLOB             NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    CONSTRAINT PERSONA_PK PRIMARY KEY (CLIENTE_ID), 
    CONSTRAINT PERSONA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE(CLIENTE_ID)
)
;



