-- @Autor: Oswaldo Cabrera Pérez y Edgar García
-- @Fecha creación: 27/12/2022
-- @Descripción: Creacion de las tablas y foreign keys de la base de datos




-- TABLE: BANCO 


WHENEVER SQLERROR EXIT ROLLBACK;

CREATE TABLE BANCO(
    BANCO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE      VARCHAR2(50)     NOT NULL,
    CONSTRAINT BANCO_PK PRIMARY KEY (BANCO_ID)
    USING INDEX (
      CREATE UNIQUE INDEX BANCO_PK ON BANCO(BANCO_ID)
      TABLESPACE INDEXES
    )
) TABLESPACE VENDOR_BANK_DATA;




-- TABLE: TIPO_SERVICIO 


CREATE TABLE TIPO_SERVICIO(
    TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(50)     NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    CONSTRAINT TIPO_SERVICIO_PK PRIMARY KEY (TIPO_SERVICIO_ID)
    USING INDEX (
      CREATE UNIQUE INDEX TIPO_SERVICIO_PK ON TIPO_SERVICIO(TIPO_SERVICIO_ID)
    TABLESPACE INDEXES)
) TABLESPACE VENDORS;


-- -- 
-- -- TABLE: ENTIDAD_FEDERATIVA 
-- --

CREATE TABLE ENTIDAD_FEDERATIVA(
    ENTIDAD_FEDERATIVA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(50)     NOT NULL,
    CONSTRAINT ENTIDAD_FEDERATIVA_PK PRIMARY KEY (ENTIDAD_FEDERATIVA_ID)
    USING INDEX (
      CREATE UNIQUE INDEX ENTIDAD_FEDERATIVA_PK ON 
        ENTIDAD_FEDERATIVA(ENTIDAD_FEDERATIVA_ID)
        TABLESPACE INDEXES
    )
) TABLESPACE VENDORS;



-- -- 
-- -- TABLE: ESTATUS_PROVEEDOR 
-- --

CREATE TABLE ESTATUS_PROVEEDOR(
    ESTATUS_PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(50)     NOT NULL,
    DESCRIPCION             VARCHAR2(500)    NOT NULL,
    CONSTRAINT ESTATUS_PROVEEDOR_PK PRIMARY KEY (ESTATUS_PROVEEDOR_ID)
    USING INDEX (
      CREATE UNIQUE INDEX STATUS_PROVEEDOR_PK ON 
        ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID)
        TABLESPACE INDEXES
    )
) TABLESPACE VENDORS;



-- -- 
-- -- TABLE: NIVEL_ESTUDIO 
-- --

CREATE TABLE NIVEL_ESTUDIO(
    NIVEL_ESTUDIO_ID    NUMBER(10, 0)    NOT NULL,
    NIVEL_ESTUDIO       VARCHAR2(200)    NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    CONSTRAINT NIVEL_ESTUDIO_PK PRIMARY KEY (NIVEL_ESTUDIO_ID)
    USING INDEX (
      CREATE UNIQUE INDEX NIVEL_ESTUDIO_PK ON 
        NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID)
        TABLESPACE INDEXES
    )
) TABLESPACE VENDORS;




-- TABLE: PROVEEDOR 



CREATE TABLE PROVEEDOR(
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(50)     NOT NULL,
    AP_PATERNO               VARCHAR2(30)     NOT NULL,
    AP_MATERNO               VARCHAR2(30)     NOT NULL,
    FOTO                     BLOB             NOT NULL,
    FECHA_NACIMIENTO         DATE             NOT NULL,
    DIRECCION                VARCHAR2(200)    NOT NULL,
    TELEFONO_CASA            NUMBER(10, 0)    NOT NULL,
    TELEFONO_MOVIL           VARCHAR2(40)     NOT NULL,
    IDENTIFICACION           BLOB             NOT NULL,
    COMPROBANTE_DOMICILIO    BLOB             NOT NULL,
    FECHA_ESTATUS            DATE             NOT NULL,
    ENTIDAD_FEDERATIVA_ID    NUMBER(10, 0)    NOT NULL,
    ESTATUS_PROVEEDOR_ID     NUMBER(10, 0)    NOT NULL,
    NIVEL_ESTUDIO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (PROVEEDOR_ID)
    USING INDEX (
      CREATE UNIQUE INDEX PROVEEDOR_PK ON 
        PROVEEDOR(PROVEEDOR_ID)
        TABLESPACE INDEXES
    ), 
    CONSTRAINT PROV_ENTIDAD_FEDERATIVA_ID_FK FOREIGN KEY (ENTIDAD_FEDERATIVA_ID)
      REFERENCES ENTIDAD_FEDERATIVA(ENTIDAD_FEDERATIVA_ID),
    CONSTRAINT PROV_ESTATUS_PROVEEDOR_ID_FK FOREIGN KEY (ESTATUS_PROVEEDOR_ID)
      REFERENCES ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID),
    CONSTRAINT PROV_NIVEL_ESTUDIO_ID_FK FOREIGN KEY (NIVEL_ESTUDIO_ID)
      REFERENCES NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID)
) 
LOB (FOTO) 
    STORE AS SECUREFILE SFSEGNAME1 (TABLESPACE MEDIA
      RETENTION AUTO
      CACHE LOGGING
      STORAGE (MAXEXTENTS 5)),
LOB (COMPROBANTE_DOMICILIO) 
    STORE AS SECUREFILE SFSEGNAME2 (TABLESPACE MEDIA
      RETENTION AUTO
      CACHE LOGGING
      STORAGE (MAXEXTENTS 5)),
LOB (IDENTIFICACION) 
    STORE AS SECUREFILE SFSEGNAME3 (TABLESPACE MEDIA
      RETENTION AUTO
      CACHE LOGGING
      STORAGE (MAXEXTENTS 5)),
TABLESPACE VENDORS;




-- TABLE: CLIENTE 
-- --

CREATE TABLE CLIENTE(
    CLIENTE_ID        NUMBER(10, 0)    NOT NULL,
    FECHA_REGISTRO    DATE             NOT NULL,
    NOMBRE_USUARIO    VARCHAR2(100)    NOT NULL,
    CONTRASENIA       VARCHAR2(500)    NOT NULL,
    EMAIL             VARCHAR2(50)     NOT NULL,
    TELEFONO          NUMBER(10, 0)    NOT NULL,
    DIRECCION         VARCHAR2(300)    NOT NULL,
    TIPO              CHAR(1)          NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
    USING INDEX (
      CREATE UNIQUE INDEX CLINTE_PK ON 
        CLIENTE(CLIENTE_ID)
        TABLESPACE INDEXES
    )
) TABLESPACE CLIENTS;



-- -- 
-- -- TABLE: ESTATUS_SERVICIO 
-- --

CREATE TABLE ESTATUS_SERVICIO(
    ESTATUS_SERVICIO_ID    CHAR(10)        NOT NULL,
    NOMBRE                 VARCHAR2(30)    NOT NULL,
    DESCRIPCION            VARCHAR2(50)    NOT NULL,
    CONSTRAINT ESTATUS_SERVICIO_PK PRIMARY KEY (ESTATUS_SERVICIO_ID)
    USING INDEX (
      CREATE UNIQUE INDEX ESTATUS_SERVICIO_PK ON 
        ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID)
        TABLESPACE INDEXES
    )
) TABLESPACE SERVICES;



-- -- -- 
-- -- -- TABLE: HISTORICO_ESTATUS_SERVICIO 
-- -- --


CREATE TABLE HISTORICO_ESTATUS_SERVICIO(
    HISTORICO_ESTATUS_SERVICIO_ID    VARCHAR2(10)    NOT NULL,
    FECHA_ESTATUS                    DATE            NOT NULL,
    ESTATUS_SERVICIO_ID              NUMBER(10,0)        NOT NULL,
    CONSTRAINT HISTORICO_ESTATUS_SERVICIO_PK 
      PRIMARY KEY (HISTORICO_ESTATUS_SERVICIO_ID)
      USING INDEX (
        CREATE UNIQUE INDEX HISTORICO_ESTATUS_SERVICIO_PK ON 
          HISTORICO_ESTATUS_SERVICIO(HISTORICO_ESTATUS_SERVICIO_ID)
          TABLESPACE INDEXES
    ),
    CONSTRAINT HES_ESTATUS_SERVICIO_ID_FK FOREIGN KEY (ESTATUS_SERVICIO_ID)
      REFERENCES ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID)
) TABLESPACE SERVICES;



-- -- 
-- -- TABLE: SERVICIO 
-- --

CREATE TABLE SERVICIO(
    SERVICIO_ID                      NUMBER(10, 0)     NOT NULL,
    FECHA_SERVICIO                   DATE              NOT NULL,
    DESCRIPCION_SERVICIO             VARCHAR2(1000)    NOT NULL,
    DESCRIPCION_DETALLADA            BLOB              NOT NULL,
    FECHA_ESTATUS                    DATE              NOT NULL,
    PRECIO                           NUMBER(10, 0)     NOT NULL,
    INSTRUCCIONES                    VARCHAR2(500)     NOT NULL,
    MENSUALIDADES                    NUMBER(10, 0),
    PROVEEDOR_ID                     NUMBER(10, 0)     NOT NULL,
    CLIENTE_ID                       NUMBER(10, 0)     NOT NULL,
    HISTORICO_ESTATUS_SERVICIO_ID    NUMBER(10, 0)     NOT NULL,
    ESTATUS_SERVICIO_ID              NUMBER(10, 0)     NOT NULL,
    TIPO_SERVICIO_ID                 NUMBER(10, 0)     NOT NULL,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (SERVICIO_ID)
    USING INDEX (
      CREATE UNIQUE INDEX SERVICIO_PK ON 
        SERVICIO(SERVICIO_ID)
        TABLESPACE INDEXES
    ), 
    CONSTRAINT SERV_TIPO_SERVICIO_ID_FK FOREIGN KEY (TIPO_SERVICIO_ID)
      REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID),
    CONSTRAINT SERV_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT SERV_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT SERV_HISTORICO_ESTATUS_SERVICIO_ID_FK 
      FOREIGN KEY (HISTORICO_ESTATUS_SERVICIO_ID)
        REFERENCES HISTORICO_ESTATUS_SERVICIO(HISTORICO_ESTATUS_SERVICIO_ID),
    CONSTRAINT SERV_ESTATUS_SERVICIO_ID_FK FOREIGN KEY (ESTATUS_SERVICIO_ID)
      REFERENCES ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID)
) 
LOB (DESCRIPCION_DETALLADA) 
    STORE AS SECUREFILE SFSEGNAME4 (TABLESPACE MEDIA
      RETENTION AUTO
      CACHE LOGGING
      STORAGE (MAXEXTENTS 5)),
TABLESPACE SERVICES;



-- -- 
-- -- TABLE: CALIFICACION 
-- --

CREATE TABLE CALIFICACION(
    CALIFICACION_ID    NUMBER(10, 0)    NOT NULL,
    COMENTARIO         VARCHAR2(500),
    CALIFICACION       NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CALIFICACION_PK PRIMARY KEY (CALIFICACION_ID)
    USING INDEX (
      CREATE UNIQUE INDEX CALIFICACION_PK ON 
        CALIFICACION(CALIFICACION_ID)
        TABLESPACE INDEXES
      ),
    CONSTRAINT CALIFICACION_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID)
      REFERENCES SERVICIO(SERVICIO_ID)
) TABLESPACE SERVICES;



-- -- 
-- -- TABLE: PROVEEDOR_TIPO_SERVICIO 
-- --

CREATE TABLE PROVEEDOR_TIPO_SERVICIO(
    PROVEEDOR_TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    ANIOS_EXPERIENCIA             NUMBER(10, 0)    NOT NULL,
    PROVEEDOR_ID                  NUMBER(10, 0)    NOT NULL,
    TIPO_SERVICIO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PROVEEDOR_TIPO_SERVICIO_PK 
      PRIMARY KEY (PROVEEDOR_TIPO_SERVICIO_ID)
      USING INDEX (
      CREATE UNIQUE INDEX PROVEEDOR_TIPO_SERVICIO_PK ON 
        PROVEEDOR_TIPO_SERVICIO(PROVEEDOR_TIPO_SERVICIO_ID)
        TABLESPACE INDEXES
      ),
    CONSTRAINT PROV_TS_TIPO_SERVICIO_ID_FK FOREIGN KEY (TIPO_SERVICIO_ID)
      REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID),
    CONSTRAINT PROV_TS_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID)
) TABLESPACE SERVICES;




-- TABLE: COMPROBANTE_EXPERIENCIA 


CREATE TABLE COMPROBANTE_EXPERIENCIA(
    COMPROBANTE_EXPERIENCIA_ID    NUMBER(10, 0)    NOT NULL,
    TITULO_COMPROBANTE            VARCHAR2(100)    NOT NULL,
    CONTENIDO                     BLOB             NOT NULL,
    FECHA_COMPROBANTE             DATE             NOT NULL,
    PROVEEDOR_TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT COMPROBANTE_EXPERIENCIA_PK 
      PRIMARY KEY (COMPROBANTE_EXPERIENCIA_ID)
      USING INDEX (
        CREATE UNIQUE INDEX COMPROBANTE_EXPERIENCIA_PK ON 
            COMPROBANTE_EXPERIENCIA(COMPROBANTE_EXPERIENCIA_ID)
            TABLESPACE INDEXES
        ),
    CONSTRAINT CE_PROVEEDOR_TIPO_SERVICIO_ID_PK 
      FOREIGN KEY (PROVEEDOR_TIPO_SERVICIO_ID)
        REFERENCES PROVEEDOR_TIPO_SERVICIO(PROVEEDOR_TIPO_SERVICIO_ID)
)
LOB (CONTENIDO) 
    STORE AS SECUREFILE SFSEGNAME5 (TABLESPACE MEDIA
      RETENTION AUTO
      CACHE LOGGING
      STORAGE (MAXEXTENTS 5)), 
TABLESPACE VENDORS;



-- -- 
-- -- TABLE: CUENTA_BANCARIA 
-- --

CREATE TABLE CUENTA_BANCARIA(
    CUENTA_BANCARIA_ID    NUMBER(10, 0)    NOT NULL,
    CLABE                 VARCHAR2(255)    NOT NULL,
    PROVEEDOR_ID          NUMBER(10, 0)    NOT NULL,
    BANCO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CUENTA_BANCARIA_PK PRIMARY KEY (CUENTA_BANCARIA_ID)
      USING INDEX (
        CREATE UNIQUE INDEX CUENTA_BANCARIA_PK ON 
          CUENTA_BANCARIA(CUENTA_BANCARIA_ID)
          TABLESPACE INDEXES
        ),
    CONSTRAINT CB_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT CB_BANCO_ID_FK FOREIGN KEY (BANCO_ID)
      REFERENCES BANCO(BANCO_ID)
) TABLESPACE VENDOR_BANK_DATA;


-- -- 
-- -- TABLE: DEPOSITO 
-- --

CREATE TABLE DEPOSITO(
    DEPOSITO_ID           NUMBER(10, 0)    NOT NULL,
    IMPORTE               NUMBER(10, 0)    NOT NULL,
    FECHA_DEPOSITO        DATE             NOT NULL,
    COMPROBANTE_PAGO      BLOB             NOT NULL,
    CUENTA_BANCARIA_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT DEPOSITO_PK PRIMARY KEY (DEPOSITO_ID)
      USING INDEX (
        CREATE UNIQUE INDEX DEPOSITO_PK ON DEPOSITO(DEPOSITO_ID)
        TABLESPACE INDEXES
      ), 
    CONSTRAINT DEPOSITO_CUENTA_BANCARIA_ID_FK FOREIGN KEY (CUENTA_BANCARIA_ID)
      REFERENCES CUENTA_BANCARIA(CUENTA_BANCARIA_ID)
) 
LOB (COMPROBANTE_PAGO) 
    STORE AS SECUREFILE SFSEGNAME6 (TABLESPACE MEDIA
      RETENTION AUTO
      CACHE LOGGING
      STORAGE (MAXEXTENTS 5)),
TABLESPACE VENDOR_BANK_DATA;




-- TABLE: EMAIL 


CREATE TABLE EMAIL(
    EMAIL_ID        NUMBER(10, 0)    NOT NULL,
    PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,
    EMAIL           VARCHAR2(200)    NOT NULL,
    CONSTRAINT EMAIL_PK PRIMARY KEY (EMAIL_ID, PROVEEDOR_ID)
      USING INDEX (
        CREATE UNIQUE INDEX EMAIL_PK ON EMAIL(EMAIL_ID, PROVEEDOR_ID)
        TABLESPACE INDEXES
       ),
    CONSTRAINT EMAIL_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID)
) TABLESPACE VENDORS;




-- TABLE: EMPRESA 


CREATE TABLE EMPRESA(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    DESCRIPCION         VARCHAR2(500)    NOT NULL,
    NOMBRE              VARCHAR2(200)    NOT NULL,
    LOGOTIPO            BLOB             NOT NULL,
    NUMERO_EMPLEADOS    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EMPRESA_PK PRIMARY KEY (CLIENTE_ID)
      USING INDEX (
        CREATE UNIQUE INDEX EMPRESA_PK ON EMPRESA(CLIENTE_ID)
        TABLESPACE INDEXES
       ), 
    CONSTRAINT EMPRESA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE(CLIENTE_ID)
) 
LOB (LOGOTIPO) 
    STORE AS SECUREFILE SFSEGNAME7 (TABLESPACE MEDIA
      RETENTION AUTO
      CACHE LOGGING
      STORAGE (MAXEXTENTS 5)),
TABLESPACE CLIENTS;



-- -- 
-- -- TABLE: EVIDENCIA_SERVICIO 
-- --

CREATE TABLE EVIDENCIA_SERVICIO(
    EVIDENCIA_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA                    DATE             NOT NULL,
    DESCRIPCION              VARCHAR2(500)    NOT NULL,
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EVIDENCIA_SERVICIO_PK PRIMARY KEY (EVIDENCIA_SERVICIO_ID)
    USING INDEX (
      CREATE UNIQUE INDEX EVIDENCIA_SERVICIO_PK ON 
        EVIDENCIA_SERVICIO(EVIDENCIA_SERVICIO_ID)
        TABLESPACE INDEXES
    ),
    CONSTRAINT EVIDENCIA_SERVICIO_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID)
      REFERENCES PROVEEDOR(PROVEEDOR_ID)
) TABLESPACE VENDORS;




-- TABLE: HISTORICO_ESTATUS_PROVEEDOR 


CREATE TABLE HISTORICO_ESTATUS_PROVEEDOR(
    HISTORICO_ESTATUS_PROVEEDOR_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_ESTATUS                     DATE             NOT NULL,
    ESTATUS_PROVEEDOR_ID              NUMBER(10, 0)    NOT NULL,
    PROVEEDOR_ID                      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_ESTATUS_PROVEEDOR_PK 
      PRIMARY KEY (HISTORICO_ESTATUS_PROVEEDOR_ID)
      USING INDEX (
       CREATE UNIQUE INDEX HISTORICO_ESTATUS_PROVEEDOR_PK ON 
         HISTORICO_ESTATUS_PROVEEDOR(HISTORICO_ESTATUS_PROVEEDOR_ID)
         TABLESPACE INDEXES
     ),
    CONSTRAINT HISTORICO_ESTATUS_PROVEEDOR_ESTATUS_PROVEEDOR_ID_FK 
      FOREIGN KEY (ESTATUS_PROVEEDOR_ID)
        REFERENCES ESTATUS_PROVEEDOR(ESTATUS_PROVEEDOR_ID),
    CONSTRAINT HISTORICO_ESTATUS_PROVEEDOR_PROVEEDOR_ID_FK 
      FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES PROVEEDOR(PROVEEDOR_ID)
) TABLESPACE VENDORS;



-- -- 
-- -- TABLE: IMAGEN 
-- --

CREATE TABLE IMAGEN(
    IMAGEN_ID                NUMBER(10, 0)    NOT NULL,
    DESCRIPCION              VARCHAR2(500),
    ARCHIVO                  BLOB             NOT NULL,
    EVIDENCIA_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT IMAGEN_PK PRIMARY KEY (IMAGEN_ID)
    USING INDEX (
       CREATE UNIQUE INDEX IMAGEN_PK ON IMAGEN(IMAGEN_ID)
       TABLESPACE INDEXES
     ),
    CONSTRAINT IMAGEN_EVUDENCIA_SERVICIO_ID_FK 
      FOREIGN KEY (EVIDENCIA_SERVICIO_ID)
        REFERENCES EVIDENCIA_SERVICIO(EVIDENCIA_SERVICIO_ID)
) 
LOB (ARCHIVO) 
    STORE AS SECUREFILE SFSEGNAME8 (TABLESPACE MEDIA
      RETENTION AUTO
      CACHE LOGGING
      STORAGE (MAXEXTENTS 5)),
TABLESPACE VENDORS;



-- -- 
-- -- TABLE: TARJETA 
-- --

CREATE TABLE TARJETA(
    TARJETA_ID          NUMBER(10, 0)    NOT NULL,
    NUMERO              NUMBER(16, 0)    NOT NULL,
    FECHA_EXPIRACION    DATE             NOT NULL,
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT TARJETA_PK PRIMARY KEY (TARJETA_ID)
    USING INDEX (
       CREATE UNIQUE INDEX TARJETA_PK ON TARJETA(TARJETA_ID)
       TABLESPACE INDEXES
    ),
    CONSTRAINT TARJETA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE(CLIENTE_ID)
) TABLESPACE CLIENT_BANK_DATA;




-- TABLE: PAGO 


CREATE TABLE PAGO(
    PAGO_ID        NUMBER(10, 0)    NOT NULL,
    TARJETA_ID     NUMBER(10, 0)    NOT NULL,
    FECHA_PAGO     DATE,
    IMPORTE        NUMBER(10, 0)    NOT NULL,
    COMISION       NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PAGO_PK PRIMARY KEY (PAGO_ID, TARJETA_ID)
    USING INDEX (
      CREATE UNIQUE INDEX PAGO_PK ON 
        PAGO(PAGO_ID, TARJETA_ID)
        TABLESPACE INDEXES
      ),
    CONSTRAINT PAGO_TARJETA_ID_FK FOREIGN KEY (TARJETA_ID)
      REFERENCES TARJETA(TARJETA_ID),
    CONSTRAINT PAGO_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID)
      REFERENCES SERVICIO(SERVICIO_ID)
) TABLESPACE CLIENT_BANK_DATA;



-- -- 
-- TABLE: PERSONA 


CREATE TABLE PERSONA(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(200)    NOT NULL,
    FOTO                BLOB             NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    CONSTRAINT PERSONA_PK PRIMARY KEY (CLIENTE_ID)
    USING INDEX (
      CREATE UNIQUE INDEX PERSONA_PK ON 
        PERSONA(CLIENTE_ID)
        TABLESPACE INDEXES
      ),
    CONSTRAINT PERSONA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID)
      REFERENCES CLIENTE(CLIENTE_ID)
)
LOB (FOTO) 
    STORE AS SECUREFILE SFSEGNAME9(TABLESPACE MEDIA
      RETENTION AUTO
      CACHE LOGGING
      STORAGE (MAXEXTENTS 5)), 
TABLESPACE CLIENTS;



