--@Autor: Oswaldo Cabrera Pérez y Edgar García
--@Fecha creación: 27/12/2022
--@Descripción: Creacion de índices y tablespaces



-- Tabla: PROVEEDOR

--índice compuesto
-- CREATE INDEX PROV_PROVEEDORES_IX
--   ON PROVEEDOR(DIRECCION, TELEFONO_CASA, TELEFONO_MOVIL) TABLESPACE INDEXES;
--Índice non unique
CREATE INDEX PROV_ENTIDAD_FEDERATIVA_ID_IX 
  ON PROVEEDOR(ENTIDAD_FEDERATIVA_ID) TABLESPACE INDEXES;
--Índice unique
CREATE UNIQUE INDEX PROV_ESTATUS_PROVEEDOR_ID_IX
  ON PROVEEDOR(ESTATUS_PROVEEDOR_ID) TABLESPACE INDEXES;

CREATE UNIQUE INDEX PROV_NIVEL_ESTUDIO_ID_IX
  ON PROVEEDOR(NIVEL_ESTUDIO_ID) TABLESPACE INDEXES;


-- Tabla: CUENTA_BANCARIA

--
CREATE INDEX CB_BANCO_ID_IX
  ON CUENTA_BANCARIA(BANCO_ID) TABLESPACE INDEXES;

--
CREATE INDEX CB_PROVEEDOR_ID_IX
  ON CUENTA_BANCARIA(PROVEEDOR_ID) TABLESPACE INDEXES;

-- Tabla: EVIDENCIA SERVICIO
CREATE INDEX PROV_ESTATUS_PROVEEDOR_ID_IX
  ON EVIDENCIA_SERVICIO(PROVEEDOR_ID) TABLESPACE INDEXES;
  
--Tabla: PROVEEDOR_TIPO_SERVICIO

CREATE INDEX PTS_PROVEEDOR_ID_IX
  ON PROVEEDOR_TIPO_SERVICIO(PROVEEDOR_ID) TABLESPACE INDEXES;

CREATE INDEX PTS_TIPO_SERVICIO_ID_IX 
  ON PROVEEDOR_TIPO_SERVICIO(TIPO_SERVICIO_ID) TABLESPACE INDEXES;

-- Tabla: COMPROBANTE_EXPERIENCIA
CREATE INDEX CE_PROVEEDOR_TIPO_SERVICIO_ID_IX
  ON COMPROBANTE_EXPERIENCIA(PROVEEDOR_TIPO_SERVICIO_ID) TABLESPACE INDEXES;

-- Tabla: DEPOSITO
CREATE INDEX DEP_CUENTA_BANCARIA_ID_IX
  ON DEPOSITO(CUENTA_BANCARIA_ID) TABLESPACE INDEXES;

--TABLESPACE: CLIENTES

--Tabla CLIENTE
CREATE UNIQUE INDEX IDX_USR_NAME
  ON CLIENTE(LOWER(NOMBRE_USUARIO)) TABLESPACE INDEXES;


--Tabla PERSONA

CREATE UNIQUE INDEX CLIENTE_CURP_IUK
   ON PERSONA(CURP) TABLESPACE INDEXES;

--Tabla TARJETA

CREATE UNIQUE INDEX TAR_NUMERO_IUK
  ON TARJETA (NUMERO) TABLESPACE INDEXES;

CREATE INDEX TAR_CLIENTE_ID_IX
  ON TARJETA(CLIENTE_ID) TABLESPACE INDEXES;
  
-- Tabla PAGO

CREATE INDEX PAGO_TARJETA_ID_IX
  ON PAGO(TARJETA_ID) TABLESPACE INDEXES;

CREATE INDEX PAGO_SERVICIO_ID_IX
 ON PAGO(SERVICIO_ID) TABLESPACE INDEXES;

-- Tabla: Servicio

CREATE INDEX SERV_PROVEEDOR_ID_IX
  ON SERVICIO(PROVEEDOR_ID) TABLESPACE INDEXES;

CREATE INDEX SERV_CLIENTE_ID_IX
  ON SERVICIO(CLIENTE_ID) TABLESPACE INDEXES;

CREATE INDEX SERV_HISTORICO_ESTATUS_SERVICIO_ID_IX
  ON SERVICIO(HISTORICO_ESTATUS_SERVICIO_ID) TABLESPACE INDEXES;

CREATE INDEX SERV_ESTATUS_SERVICIO_ID_IX
  ON SERVICIO(ESTATUS_SERVICIO_ID) TABLESPACE INDEXES;
   
CREATE INDEX SERV_TIPO_SERVICIO_ID_IX
  ON SERVICIO(TIPO_SERVICIO_ID) TABLESPACE INDEXES;
  
-- Tabla HISTORICO_ESTATUS_SERVICIO
CREATE INDEX HES_ESTATUS_SERVICIO_ID_IX
  ON HISTORICO_ESTATUS_SERVICIO(ESTATUS_SERVICIO_ID) TABLESPACE INDEXES;

--Tabla CALIFICACION

CREATE INDEX CALIFICACION_SERVICIO_ID_IX
  ON CALIFICACION(SERVICIO_ID) TABLESPACE INDEXES;